// Generated by CoffeeScript 1.10.0
var azrs, commands, news;

commands = {};

news = {};

azrs = [];

$(function() {
  var i, j;
  $.getJSON("/data/commands.json", function(json) {
    commands = json;
  });
  $.getJSON("/data/news.json", function(json) {
    news = json;
  });
  for (i = j = 1; j <= 3; i = ++j) {
    $.get("/data/azrs/" + i + ".txt", function(data) {
      return azrs.push(data);
    });
  }
  $('#terminal').terminal((function(command, term) {
    var course, index, k, len, ref, value;
    if (command !== '') {
      if (command in commands) {
        switch (command) {
          case "quit":
            term.echo(new String("Good bye!"));
            window.open("http://www.it-college.ac.jp/");
            break;
          case "help":
            for (value in commands) {
              index = commands[value];
              term.echo(new String("* " + value + ": " + index.desc));
            }
            break;
          case "news":
            for (value in news) {
              index = news[value];
              term.echo(new String("* " + index.title + ": " + index.url));
            }
            break;
          case "twitter":
            window.open(commands.twitter.content);
            break;
          case "facebook":
            window.open(commands.facebook.content);
            break;
          case "reload":
            location.reload(true);
            break;
          case "map":
            window.open(commands.map.content);
            break;
          case "ls":
            term.echo(new String("Course list:"));
            ref = commands.ls.content;
            for (k = 0, len = ref.length; k < len; k++) {
              course = ref[k];
              term.echo(new String("* " + course + "\t"));
            }
            break;
          case "azrs":
            term.echo(new String(azrs[Math.floor(Math.random() * azrs.length)]));
            break;
          default:
            term.echo(new String(commands[command].content));
        }
      } else {
        term.error(new String("Command Not Found: " + command));
      }
    } else {
      term.echo('');
    }
  }), {
    greetings: "Welcome To IT-College Okinawa http://www.it-college.ac.jp\nUsage: help",
    name: 'js_demo',
    height: $(window).height(),
    prompt: 'it-college$ '
  });
});
